name: generate-snake

on:
  schedule:
    # 每 6 小时，执行一次
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate github-snake.svg
        uses: Platane/snk@v2.2.1
        with:
          # 你的 GitHub 的名称
          github_user_name: jijunhao
          # 生成的 .gif 图存储的位置
          gif_out_path: dist/github-snake.gif
          # 生成的 .gif 图存储的位置
          svg_out_path: dist/github-snake.svg
      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
