name: generate-snake

on:
  schedule:
    - cron: '* 0 * * *'
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate github-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          # 你的 GitHub 的名称
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
